-- ============================================================
-- Workaround for Langfuse bug #11924:
-- events_core and events_full are missing from production
-- ClickHouse migrations. This script creates them as VIEWs
-- over the existing observations + traces tables.
--
-- Mounted and executed by the clickhouse-init-views service
-- in docker-compose.yml on every stack startup.
-- ============================================================

CREATE OR REPLACE VIEW default.events_core AS
-- Observation-level rows
SELECT
    o.project_id                                                                        AS project_id,
    o.trace_id                                                                          AS trace_id,
    o.id                                                                                AS span_id,
    coalesce(o.parent_observation_id, concat('t-', o.trace_id))                         AS parent_span_id,
    o.start_time                                                                        AS start_time,
    o.end_time                                                                          AS end_time,
    o.name                                                                              AS name,
    o.type                                                                              AS type,
    o.environment                                                                       AS environment,
    coalesce(o.version, t.version)                                                      AS version,
    coalesce(t.release, '')                                                             AS release,
    t.name                                                                              AS trace_name,
    coalesce(t.user_id, '')                                                             AS user_id,
    coalesce(t.session_id, '')                                                          AS session_id,
    t.tags                                                                              AS tags,
    o.level                                                                             AS level,
    coalesce(o.status_message, '')                                                      AS status_message,
    o.completion_start_time                                                             AS completion_start_time,
    toUInt8(0)                                                                          AS bookmarked,
    t.public                                                                            AS public,
    o.prompt_id                                                                         AS prompt_id,
    o.prompt_name                                                                       AS prompt_name,
    o.prompt_version                                                                    AS prompt_version,
    o.internal_model_id                                                                 AS model_id,
    o.provided_model_name                                                               AS provided_model_name,
    coalesce(o.model_parameters, '{}')                                                  AS model_parameters,
    o.provided_usage_details                                                            AS provided_usage_details,
    o.usage_details                                                                     AS usage_details,
    o.provided_cost_details                                                             AS provided_cost_details,
    o.cost_details                                                                      AS cost_details,
    coalesce(o.total_cost, toDecimal64(0, 12))                                          AS total_cost,
    arraySum(mapValues(mapFilter(x -> positionCaseInsensitive(x.1, 'input') > 0, o.cost_details)))  AS calculated_input_cost,
    arraySum(mapValues(mapFilter(x -> positionCaseInsensitive(x.1, 'output') > 0, o.cost_details))) AS calculated_output_cost,
    o.usage_pricing_tier_id                                                             AS usage_pricing_tier_id,
    o.usage_pricing_tier_name                                                           AS usage_pricing_tier_name,
    o.tool_definitions                                                                  AS tool_definitions,
    o.tool_calls                                                                        AS tool_calls,
    o.tool_call_names                                                                   AS tool_call_names,
    leftUTF8(coalesce(o.input, ''), 200)                                                AS input,
    lengthUTF8(coalesce(o.input, ''))                                                   AS input_length,
    leftUTF8(coalesce(o.output, ''), 200)                                               AS output,
    lengthUTF8(coalesce(o.output, ''))                                                  AS output_length,
    mapKeys(mapConcat(o.metadata, coalesce(t.metadata, map())))                         AS metadata_names,
    arrayMap(v -> leftUTF8(v, 200), mapValues(mapConcat(o.metadata, coalesce(t.metadata, map())))) AS metadata_values,
    ''                                                                                  AS experiment_id,
    ''                                                                                  AS experiment_name,
    CAST([] AS Array(String))                                                           AS experiment_metadata_names,
    CAST([] AS Array(String))                                                           AS experiment_metadata_values,
    ''                                                                                  AS experiment_description,
    ''                                                                                  AS experiment_dataset_id,
    ''                                                                                  AS experiment_item_id,
    CAST(NULL AS Nullable(DateTime64(6)))                                               AS experiment_item_version,
    ''                                                                                  AS experiment_item_expected_output,
    CAST([] AS Array(String))                                                           AS experiment_item_metadata_names,
    CAST([] AS Array(String))                                                           AS experiment_item_metadata_values,
    ''                                                                                  AS experiment_item_root_span_id,
    ''                                                                                  AS source,
    ''                                                                                  AS service_name,
    ''                                                                                  AS service_version,
    ''                                                                                  AS scope_name,
    ''                                                                                  AS scope_version,
    ''                                                                                  AS telemetry_sdk_language,
    ''                                                                                  AS telemetry_sdk_name,
    ''                                                                                  AS telemetry_sdk_version,
    ''                                                                                  AS blob_storage_file_path,
    toUInt64(0)                                                                         AS event_bytes,
    o.created_at                                                                        AS created_at,
    o.updated_at                                                                        AS updated_at,
    o.event_ts                                                                          AS event_ts,
    o.is_deleted                                                                        AS is_deleted
FROM default.observations o FINAL
LEFT JOIN default.traces t ON o.project_id = t.project_id AND o.trace_id = t.id
WHERE o.is_deleted = 0

UNION ALL

-- Synthetic trace-level root spans from the traces table
SELECT
    t.project_id                                                                        AS project_id,
    t.id                                                                                AS trace_id,
    concat('t-', t.id)                                                                  AS span_id,
    ''                                                                                  AS parent_span_id,
    t.timestamp                                                                         AS start_time,
    CAST(NULL AS Nullable(DateTime64(3)))                                               AS end_time,
    t.name                                                                              AS name,
    'TRACE'                                                                             AS type,
    t.environment                                                                       AS environment,
    coalesce(t.version, '')                                                             AS version,
    coalesce(t.release, '')                                                             AS release,
    t.name                                                                              AS trace_name,
    coalesce(t.user_id, '')                                                             AS user_id,
    coalesce(t.session_id, '')                                                          AS session_id,
    t.tags                                                                              AS tags,
    ''                                                                                  AS level,
    ''                                                                                  AS status_message,
    CAST(NULL AS Nullable(DateTime64(3)))                                               AS completion_start_time,
    t.bookmarked                                                                        AS bookmarked,
    t.public                                                                            AS public,
    CAST(NULL AS Nullable(String))                                                      AS prompt_id,
    CAST(NULL AS Nullable(String))                                                      AS prompt_name,
    CAST(NULL AS Nullable(UInt16))                                                      AS prompt_version,
    CAST(NULL AS Nullable(String))                                                      AS model_id,
    CAST(NULL AS Nullable(String))                                                      AS provided_model_name,
    '{}'                                                                                AS model_parameters,
    CAST(map() AS Map(LowCardinality(String), UInt64))                                  AS provided_usage_details,
    CAST(map() AS Map(LowCardinality(String), UInt64))                                  AS usage_details,
    CAST(map() AS Map(LowCardinality(String), Decimal(18, 12)))                         AS provided_cost_details,
    CAST(map() AS Map(LowCardinality(String), Decimal(18, 12)))                         AS cost_details,
    toDecimal64(0, 12)                                                                  AS total_cost,
    toDecimal128(0, 12)                                                                 AS calculated_input_cost,
    toDecimal128(0, 12)                                                                 AS calculated_output_cost,
    CAST(NULL AS Nullable(String))                                                      AS usage_pricing_tier_id,
    CAST(NULL AS Nullable(String))                                                      AS usage_pricing_tier_name,
    CAST(map() AS Map(String, String))                                                  AS tool_definitions,
    CAST([] AS Array(String))                                                           AS tool_calls,
    CAST([] AS Array(String))                                                           AS tool_call_names,
    leftUTF8(coalesce(t.input, ''), 200)                                                AS input,
    lengthUTF8(coalesce(t.input, ''))                                                   AS input_length,
    leftUTF8(coalesce(t.output, ''), 200)                                               AS output,
    lengthUTF8(coalesce(t.output, ''))                                                  AS output_length,
    mapKeys(coalesce(t.metadata, map()))                                                AS metadata_names,
    arrayMap(v -> leftUTF8(v, 200), mapValues(coalesce(t.metadata, map())))             AS metadata_values,
    ''                                                                                  AS experiment_id,
    ''                                                                                  AS experiment_name,
    CAST([] AS Array(String))                                                           AS experiment_metadata_names,
    CAST([] AS Array(String))                                                           AS experiment_metadata_values,
    ''                                                                                  AS experiment_description,
    ''                                                                                  AS experiment_dataset_id,
    ''                                                                                  AS experiment_item_id,
    CAST(NULL AS Nullable(DateTime64(6)))                                               AS experiment_item_version,
    ''                                                                                  AS experiment_item_expected_output,
    CAST([] AS Array(String))                                                           AS experiment_item_metadata_names,
    CAST([] AS Array(String))                                                           AS experiment_item_metadata_values,
    ''                                                                                  AS experiment_item_root_span_id,
    ''                                                                                  AS source,
    ''                                                                                  AS service_name,
    ''                                                                                  AS service_version,
    ''                                                                                  AS scope_name,
    ''                                                                                  AS scope_version,
    ''                                                                                  AS telemetry_sdk_language,
    ''                                                                                  AS telemetry_sdk_name,
    ''                                                                                  AS telemetry_sdk_version,
    ''                                                                                  AS blob_storage_file_path,
    toUInt64(0)                                                                         AS event_bytes,
    t.created_at                                                                        AS created_at,
    t.updated_at                                                                        AS updated_at,
    t.event_ts                                                                          AS event_ts,
    t.is_deleted                                                                        AS is_deleted
FROM default.traces t FINAL
WHERE t.is_deleted = 0;


-- events_full VIEW (full I/O, no truncation)
CREATE OR REPLACE VIEW default.events_full AS
-- Observation-level rows (full I/O)
SELECT
    o.project_id                                                                        AS project_id,
    o.trace_id                                                                          AS trace_id,
    o.id                                                                                AS span_id,
    coalesce(o.parent_observation_id, concat('t-', o.trace_id))                         AS parent_span_id,
    o.start_time                                                                        AS start_time,
    o.end_time                                                                          AS end_time,
    o.name                                                                              AS name,
    o.type                                                                              AS type,
    o.environment                                                                       AS environment,
    coalesce(o.version, t.version)                                                      AS version,
    coalesce(t.release, '')                                                             AS release,
    t.name                                                                              AS trace_name,
    coalesce(t.user_id, '')                                                             AS user_id,
    coalesce(t.session_id, '')                                                          AS session_id,
    t.tags                                                                              AS tags,
    o.level                                                                             AS level,
    coalesce(o.status_message, '')                                                      AS status_message,
    o.completion_start_time                                                             AS completion_start_time,
    toUInt8(0)                                                                          AS bookmarked,
    t.public                                                                            AS public,
    o.prompt_id                                                                         AS prompt_id,
    o.prompt_name                                                                       AS prompt_name,
    o.prompt_version                                                                    AS prompt_version,
    o.internal_model_id                                                                 AS model_id,
    o.provided_model_name                                                               AS provided_model_name,
    coalesce(o.model_parameters, '{}')                                                  AS model_parameters,
    o.provided_usage_details                                                            AS provided_usage_details,
    o.usage_details                                                                     AS usage_details,
    o.provided_cost_details                                                             AS provided_cost_details,
    o.cost_details                                                                      AS cost_details,
    coalesce(o.total_cost, toDecimal64(0, 12))                                          AS total_cost,
    o.usage_pricing_tier_id                                                             AS usage_pricing_tier_id,
    o.usage_pricing_tier_name                                                           AS usage_pricing_tier_name,
    o.tool_definitions                                                                  AS tool_definitions,
    o.tool_calls                                                                        AS tool_calls,
    o.tool_call_names                                                                   AS tool_call_names,
    coalesce(o.input, '')                                                               AS input,
    coalesce(o.output, '')                                                              AS output,
    mapKeys(mapConcat(o.metadata, coalesce(t.metadata, map())))                         AS metadata_names,
    mapValues(mapConcat(o.metadata, coalesce(t.metadata, map())))                       AS metadata_values,
    ''                                                                                  AS experiment_id,
    ''                                                                                  AS experiment_name,
    CAST([] AS Array(String))                                                           AS experiment_metadata_names,
    CAST([] AS Array(String))                                                           AS experiment_metadata_values,
    ''                                                                                  AS experiment_description,
    ''                                                                                  AS experiment_dataset_id,
    ''                                                                                  AS experiment_item_id,
    CAST(NULL AS Nullable(DateTime64(6)))                                               AS experiment_item_version,
    ''                                                                                  AS experiment_item_expected_output,
    CAST([] AS Array(String))                                                           AS experiment_item_metadata_names,
    CAST([] AS Array(String))                                                           AS experiment_item_metadata_values,
    ''                                                                                  AS experiment_item_root_span_id,
    ''                                                                                  AS source,
    ''                                                                                  AS service_name,
    ''                                                                                  AS service_version,
    ''                                                                                  AS scope_name,
    ''                                                                                  AS scope_version,
    ''                                                                                  AS telemetry_sdk_language,
    ''                                                                                  AS telemetry_sdk_name,
    ''                                                                                  AS telemetry_sdk_version,
    ''                                                                                  AS blob_storage_file_path,
    toUInt64(0)                                                                         AS event_bytes,
    o.created_at                                                                        AS created_at,
    o.updated_at                                                                        AS updated_at,
    o.event_ts                                                                          AS event_ts,
    o.is_deleted                                                                        AS is_deleted
FROM default.observations o FINAL
LEFT JOIN default.traces t ON o.project_id = t.project_id AND o.trace_id = t.id
WHERE o.is_deleted = 0

UNION ALL

-- Synthetic trace-level root spans (full I/O)
SELECT
    t.project_id                                                                        AS project_id,
    t.id                                                                                AS trace_id,
    concat('t-', t.id)                                                                  AS span_id,
    ''                                                                                  AS parent_span_id,
    t.timestamp                                                                         AS start_time,
    CAST(NULL AS Nullable(DateTime64(3)))                                               AS end_time,
    t.name                                                                              AS name,
    'TRACE'                                                                             AS type,
    t.environment                                                                       AS environment,
    coalesce(t.version, '')                                                             AS version,
    coalesce(t.release, '')                                                             AS release,
    t.name                                                                              AS trace_name,
    coalesce(t.user_id, '')                                                             AS user_id,
    coalesce(t.session_id, '')                                                          AS session_id,
    t.tags                                                                              AS tags,
    ''                                                                                  AS level,
    ''                                                                                  AS status_message,
    CAST(NULL AS Nullable(DateTime64(3)))                                               AS completion_start_time,
    t.bookmarked                                                                        AS bookmarked,
    t.public                                                                            AS public,
    CAST(NULL AS Nullable(String))                                                      AS prompt_id,
    CAST(NULL AS Nullable(String))                                                      AS prompt_name,
    CAST(NULL AS Nullable(UInt16))                                                      AS prompt_version,
    CAST(NULL AS Nullable(String))                                                      AS model_id,
    CAST(NULL AS Nullable(String))                                                      AS provided_model_name,
    '{}'                                                                                AS model_parameters,
    CAST(map() AS Map(LowCardinality(String), UInt64))                                  AS provided_usage_details,
    CAST(map() AS Map(LowCardinality(String), UInt64))                                  AS usage_details,
    CAST(map() AS Map(LowCardinality(String), Decimal(18, 12)))                         AS provided_cost_details,
    CAST(map() AS Map(LowCardinality(String), Decimal(18, 12)))                         AS cost_details,
    toDecimal64(0, 12)                                                                  AS total_cost,
    CAST(NULL AS Nullable(String))                                                      AS usage_pricing_tier_id,
    CAST(NULL AS Nullable(String))                                                      AS usage_pricing_tier_name,
    CAST(map() AS Map(String, String))                                                  AS tool_definitions,
    CAST([] AS Array(String))                                                           AS tool_calls,
    CAST([] AS Array(String))                                                           AS tool_call_names,
    coalesce(t.input, '')                                                               AS input,
    coalesce(t.output, '')                                                              AS output,
    mapKeys(coalesce(t.metadata, map()))                                                AS metadata_names,
    mapValues(coalesce(t.metadata, map()))                                              AS metadata_values,
    ''                                                                                  AS experiment_id,
    ''                                                                                  AS experiment_name,
    CAST([] AS Array(String))                                                           AS experiment_metadata_names,
    CAST([] AS Array(String))                                                           AS experiment_metadata_values,
    ''                                                                                  AS experiment_description,
    ''                                                                                  AS experiment_dataset_id,
    ''                                                                                  AS experiment_item_id,
    CAST(NULL AS Nullable(DateTime64(6)))                                               AS experiment_item_version,
    ''                                                                                  AS experiment_item_expected_output,
    CAST([] AS Array(String))                                                           AS experiment_item_metadata_names,
    CAST([] AS Array(String))                                                           AS experiment_item_metadata_values,
    ''                                                                                  AS experiment_item_root_span_id,
    ''                                                                                  AS source,
    ''                                                                                  AS service_name,
    ''                                                                                  AS service_version,
    ''                                                                                  AS scope_name,
    ''                                                                                  AS scope_version,
    ''                                                                                  AS telemetry_sdk_language,
    ''                                                                                  AS telemetry_sdk_name,
    ''                                                                                  AS telemetry_sdk_version,
    ''                                                                                  AS blob_storage_file_path,
    toUInt64(0)                                                                         AS event_bytes,
    t.created_at                                                                        AS created_at,
    t.updated_at                                                                        AS updated_at,
    t.event_ts                                                                          AS event_ts,
    t.is_deleted                                                                        AS is_deleted
FROM default.traces t FINAL
WHERE t.is_deleted = 0;
