import uuid
from langchain_ollama import ChatOllama

import config
from db.vector_db_manager import VectorDbManager
from db.parent_store_manager import ParentStoreManager
from document_chunker import DocumentChuncker
from rag_agent.tools import ToolFactory
from rag_agent.graph import create_agent_graph

# ── RAGWatch: observability setup ────────────────────────────────────────────
import base64
import os

from pathlib import Path
from dotenv import load_dotenv

# Resolve .env relative to this file: project/core/rag_system.py → ../../.env
load_dotenv(Path(__file__).parent.parent.parent / ".env")

from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter

import ragwatch
from ragwatch import RAGWatchConfig


def _langfuse_exporter():
    """Build an OTLP exporter pointed at Langfuse (self-hosted or cloud).

    Returns None and prints a warning if credentials are not set — the app
    will still start and send traces to Phoenix.

    Reads credentials from environment variables:
        LANGFUSE_PUBLIC_KEY  — Langfuse project public key  (pk-lf-…)
        LANGFUSE_SECRET_KEY  — Langfuse project secret key  (sk-lf-…)
        LANGFUSE_HOST        — Base URL (default: http://localhost:3000)
                               Override to https://cloud.langfuse.com for Langfuse Cloud.
    """
    pk   = os.getenv("LANGFUSE_PUBLIC_KEY", "")
    sk   = os.getenv("LANGFUSE_SECRET_KEY", "")
    if not pk or not sk:
        print(
            "[RAGWatch] Langfuse exporter disabled — LANGFUSE_PUBLIC_KEY / "
            "LANGFUSE_SECRET_KEY not set.\n"
            "  These are LOCAL keys generated by your own Docker container, "
            "not cloud credentials.\n"
            "  One-time setup: docker compose up -d → http://localhost:3000 "
            "→ sign up → create project → Settings → API Keys → paste into .env "
            "→ restart app."
        )
        return None
    host = os.getenv("LANGFUSE_HOST", "http://localhost:3000").rstrip("/")
    endpoint = f"{host}/api/public/otel/v1/traces"
    auth = base64.b64encode(f"{pk}:{sk}".encode()).decode()
    print(f"[RAGWatch] Langfuse exporter → {endpoint}  (pk: {pk[:12]}…)")

    exporter = OTLPSpanExporter(
        endpoint=endpoint,
        headers={"Authorization": f"Basic {auth}"},
        timeout=30,
    )

    # Hook into the underlying requests.Session to log the full response body
    # on any non-2xx — the default OTLP exporter only logs the status phrase.
    def _log_response(resp, *args, **kwargs):
        if not resp.ok:
            print(
                f"[RAGWatch/Langfuse] ✗ HTTP {resp.status_code} from {resp.url}\n"
                f"  Response body: {resp.text[:600]}"
            )
        return resp

    exporter._session.hooks["response"].append(_log_response)
    return exporter


_exporters = [
    OTLPSpanExporter(endpoint="http://localhost:6006/v1/traces"),  # Phoenix (always on)
]
_lf = _langfuse_exporter()
if _lf:
    _exporters.append(_lf)

ragwatch.configure(
    RAGWatchConfig(
        service_name="agentic-rag-for-dummies",
        exporters=_exporters,
    )
)

# ─────────────────────────────────────────────────────────────────────────────

class RAGSystem:
    
    def __init__(self, collection_name=config.CHILD_COLLECTION):
        self.collection_name = collection_name
        self.vector_db = VectorDbManager()
        self.parent_store = ParentStoreManager()
        self.chunker = DocumentChuncker()
        self.agent_graph = None
        self.thread_id = str(uuid.uuid4())
        self.recursion_limit = 50
        
    def initialize(self):
        self.vector_db.create_collection(self.collection_name)
        collection = self.vector_db.get_collection(self.collection_name)
        
        llm = ChatOllama(model=config.LLM_MODEL, temperature=config.LLM_TEMPERATURE)
        tools = ToolFactory(collection).create_tools()
        self.agent_graph = create_agent_graph(llm, tools)
        
    def get_config(self):
        return {"configurable": {"thread_id": self.thread_id}, "recursion_limit": self.recursion_limit}
    
    def reset_thread(self):
        try:
            self.agent_graph.checkpointer.delete_thread(self.thread_id)
        except Exception as e:
            print(f"Warning: Could not delete thread {self.thread_id}: {e}")
        self.thread_id = str(uuid.uuid4())